-- Batch 14.9.4: operational error / failed-job ledger.
-- Metadata only: never stores request bodies, passwords, JWTs, prompts, OCR text or translated content.

CREATE TABLE admin_error_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    severity VARCHAR(20) NOT NULL,
    module VARCHAR(30) NOT NULL,
    error_code VARCHAR(80) NOT NULL,
    exception_type VARCHAR(190) NULL,
    summary VARCHAR(500) NOT NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    actor_user_id BIGINT NULL,
    request_id VARCHAR(100) NULL,
    http_status INT NULL,
    http_method VARCHAR(12) NULL,
    request_path VARCHAR(500) NULL,
    remote_ip VARCHAR(64) NULL,
    forwarded_for VARCHAR(500) NULL,
    user_agent VARCHAR(500) NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    acknowledged_by_user_id BIGINT NULL,
    acknowledged_at TIMESTAMP(6) NULL,
    acknowledgement_note VARCHAR(500) NULL,
    resolved_by_user_id BIGINT NULL,
    resolved_at TIMESTAMP(6) NULL,
    resolution_note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    KEY idx_admin_error_status_occurred (status, occurred_at),
    KEY idx_admin_error_severity_occurred (severity, occurred_at),
    KEY idx_admin_error_module_occurred (module, occurred_at),
    KEY idx_admin_error_code_occurred (error_code, occurred_at),
    KEY idx_admin_error_request_id (request_id),
    CONSTRAINT fk_admin_error_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_admin_error_ack_by FOREIGN KEY (acknowledged_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_admin_error_resolved_by FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_admin_error_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    CONSTRAINT chk_admin_error_severity CHECK (severity IN ('WARNING', 'CRITICAL')),
    CONSTRAINT chk_admin_error_module CHECK (module IN ('HTTP', 'AI', 'PAYMENT', 'REVENUE', 'JOB', 'ADMIN', 'SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
